"""Initial migration

Revision ID: 924ea4e80382
Revises: 
Create Date: 2025-09-14 14:25:13.929766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '924ea4e80382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_supabase_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tones_name', table_name='tones')
    op.drop_index('ix_tones_user_id', table_name='tones')
    op.drop_table('tones')
    op.drop_index('ix_external_service_urls_service_name', table_name='external_service_urls')
    op.drop_table('external_service_urls')
    op.drop_index('ix_replies_created_at', table_name='replies')
    op.drop_index('ix_replies_service_type', table_name='replies')
    op.drop_index('ix_replies_tone_type', table_name='replies')
    op.drop_index('ix_replies_user_id', table_name='replies')
    op.drop_table('replies')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('writing_style', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guardian_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_settings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_settings_pkey')
    )
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=True)
    op.create_table('replies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tone_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='replies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replies_pkey')
    )
    op.create_index('ix_replies_user_id', 'replies', ['user_id'], unique=False)
    op.create_index('ix_replies_tone_type', 'replies', ['tone_type'], unique=False)
    op.create_index('ix_replies_service_type', 'replies', ['service_type'], unique=False)
    op.create_index('ix_replies_created_at', 'replies', ['created_at'], unique=False)
    op.create_table('external_service_urls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_checked', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cache_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('service_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='external_service_urls_pkey')
    )
    op.create_index('ix_external_service_urls_service_name', 'external_service_urls', ['service_name'], unique=True)
    op.create_table('tones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_preset', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tones_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tones_pkey')
    )
    op.create_index('ix_tones_user_id', 'tones', ['user_id'], unique=False)
    op.create_index('ix_tones_name', 'tones', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supabase_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_supabase_user_id', 'users', ['supabase_user_id'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###